version: '3'

services:
  mysql:
    container_name: simblue.local.db
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "soolung"
      MYSQL_PASSWORD: "soolung"
      MYSQL_DATABASE: "soolung_simblue"
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:7.0-alpine
    container_name: simblue.local.redis
    hostname: soolung
    command: /bin/sh -c "redis-server --requirepass soolung"
    env_file:
      - .env
    ports:
      - "6379:6379"