version: '3'

services:
  mysql:
    container_name: soolung_simblue_local
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: "soolung"
      MYSQL_PASSWORD: "soolung"
      MYSQL_DATABASE: "soolung_simblue"
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:latest
    container_name: soolung_simblue_redis
    hostname: soolung
    command: redis-server --port 6379
    ports:
      - "6379:6379"