version: '3'

services:
  postgresql:
    container_name: simblue.local.db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "soolung"
      POSTGRES_PASSWORD: "soolung"
      POSTGRES_DB: "soolung_simblue"
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0-alpine
    container_name: simblue.local.redis
    hostname: soolung
    command: /bin/sh -c "redis-server --requirepass soolung"
    env_file:
      - .env
    ports:
      - "6379:6379"