version: "3"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - simblue-application
    environment:
      - TZ="Asia/Seoul"
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  simblue-database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    volumes:
      - simblue-volume:/var/lib/mysql
    ports:
      - 3306:3306
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  simblue-redis:
    image: redis:latest
    container_name: soolung_simblue_redis
    hostname: soolung
    command: redis-server --port 6379
    ports:
      - "6379:6379"

  simblue-application:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    expose:
      - 8080
    env_file:
      - .env
    depends_on:
      - simblue-database
    environment:
      - TZ="Asia/Seoul"

  certbot:
    image: certbot/certbot
    container_name: certbot_service
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  simblue-volume: { }
