version: '3'

services:
  mysql:
    container_name: simblue.dev.db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    volumes:
      - simblue-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis:7.0-alpine
    container_name: simblue.dev.redis
    hostname: soolung
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379

  application:
    container_name: simblue.dev.app
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    expose:
      - 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    restart: on-failure
    environment:
      - TZ="Asia/Seoul"

volumes:
  simblue-volume: { }
