spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
#    show-sql: ㄹtrue
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

debug: true

auth:
  google:
    base-url: ${GOOGLE_BASE_URL}
    client-id: ${GOOGLE_CLIENT}
    client-secret: ${GOOGLE_SECRET}
    redirect-url: ${GOOGLE_REDIRECT}

jwt:
  access-token-valid-time: ${JWT_ACCESS_TIME}
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT_SECRET}