name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: app.soolung/simblue-application
          stage: main
          yaml: |
            name: simblue-server
            app: java@11
            options:
              ports: 8080
              env:
                - name: DB_NAME
                  value: ${{ secrets.DB_NAME }}
                - name: DB_USERNAME
                  value: ${{ secrets.DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: DB_HOST
                  value: ${{ secrets.DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
                - name: JWT_SECRET
                  value: ${{ secrets.JWT_SECRET }}
                - name: GOOGLE_BASE_URL
                  value: ${{ secrets.GOOGLE_BASE_URL }}
                - name: GOOGLE_CLIENT
                  value: ${{ secrets.GOOGLE_CLIENT }}
                - name: GOOGLE_SECRET
                  value: ${{ secrets.GOOGLE_SECRET }}
                - name: SIMBLUE_GOOGLE_REDIRECT
                  value: ${{ secrets.SIMBLUE_GOOGLE_REDIRECT }}
                - name: SSAMBLUE_GOOGLE_REDIRECT
                  value: ${{ secrets.SSAMBLUE_GOOGLE_REDIRECT }}
                - name: BUCKET_NAME 
                  value: ${{ secrets.BUCKET_NAME }}
                - name: S3_REGION 
                  value: ${{ secrets.S3_REGION }}
                - name: S3_ACCESS_KEY
                  value: ${{ secrets.S3_ACCESS_KEY }}
                - name: S3_SECRET_KEY
                  value: ${{ secrets.S3_SECRET_KEY }}
                - name: REDIS_HOST
                  value: ${{ secrets.REDIS_HOST }}
                - name: REDIS_PORT
                  value: ${{ secrets.REDIS_PORT }}
                - name: REDIS_PASSWORD
                  value: ${{ secrets.REDIS_PASSWORD }}
                - name: SPRING_PROFILES_ACTIVE
                  value: prod
                - name: TZ
                  value: Asia/Seoul
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
